### ISSUE TITLE
Data offline?

### ISSUE THREAD

**Issue by jeroenboeye** [bnosac/BelgiumMaps.StatBel#2]
Dag @jwijffels!

Zou het kunnen dat de data niet langer online staat? http://datatailor.be/ lijkt offline te zijn.

Mvg,
Jeroen

**Comment by jwijffels** [comment]
Hi @jeroenboeye 
Thanks for informing me. On Saturday the website was still working. I'm checking with the hosting provider in Anderlecht what is causing the issue.

**Comment by jwijffels** [comment]
Server went down on last Sunday due to power issues. A new power cable is now put in place. The server and services are running now as normal again. 
Thanks for creating the issue.

**Comment by jeroenboeye** [comment]
great, thanks for the quick response!
